#查询系列api，每6小时调用一次（周六日不启动）
name: Run Api.Read

on: 
  schedule:
    - cron: '12 */6 * * 1-5'
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install requests #安装requests模块
      run: |
        pip install requests
    - name: run api.Read #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息(修改以下，复制增加账号)
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python ApiOfRead.py
