#每周1，4，6自动更新refresh_token
name: Update Token

on: 
  schedule:
    - cron: '10 10 * * 1,4,6'
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests和nacl模块
      run: |
        pip install requests
        pip install PyNaCl
    - name: update secrets #更新token到secret
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息（修改以下，类推复制增加）
        APP_NUM: ${{ secrets.APP_NUM }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python UpdateToken.py
